# frozen_string_literal: true

module AnchorMigrations
  class Generator
    BASE_DIR = "anchor_migrations/sql"

    def generate
      output_file = "#{BASE_DIR}/#{rails_style_timestamp}_anchor_migration.sql"
      File.write(output_file, sql_migration_template)
      puts "Wrote file: #{output_file}"
      puts File.read(output_file)
    end

    def rails_style_timestamp
      Time.now.utc.strftime("%Y%m%d%H%M%S")
    end

    def sql_migration_template
      template = <<~SQL_TEMPLATE.strip
        -- Generated by anchor_migrations #{VERSION}
        --
        -- Examples:
        -- CREATE INDEX CONCURRENTLY IF NOT EXISTS
        -- idx_tbl_col ON tbl (col);
        --
        -- ALTER TABLE tbl
        -- ADD COLUMN IF NOT EXISTS col TEXT;
      SQL_TEMPLATE
    end
  end
end
